name: build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Gradle 8.8 → kompatibel mit Loom 1.7.x
      - name: Build with Gradle 8.8
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          arguments: clean build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lavafurnace-build
          path: build/libs/*.jar
